export default defineAppConfig({
  icons: {
    colorMode: {
      system: 'lucide:device-laptop',
      dark: 'lucide:moon',
      light: 'lucide:sun',
    },
    close: 'lucide:x',
    edit: 'lucide:pencil',
    editImage: 'lucide:image-down',
    menu: 'lucide:menu',
    search: 'lucide:search',
    link: 'lucide:link',
    github: 'simple-icons:github',
    heart: 'lucide:heart',
    arrowRight: 'lucide:chevron-right',
    arrowDown: 'lucide:chevron-down',
    arrowUp: 'lucide:chevron-up',
    plus: 'lucide:plus',
    minus: 'lucide:minus',
    check: 'lucide:check',
    clock: 'lucide:clock',
    discount: 'lucide:percent',
    delivery: 'lucide:truck',
    info: 'lucide:info',
    alert: 'lucide:triangle-alert',
    bike: 'lucide:bike',
    undo: 'lucide:undo-2',
    basket: 'lucide:shopping-basket',
    maintenance: 'lucide:traffic-cone',
    dashboard: 'lucide:layout-dashboard',
    image: 'lucide:image',
    box: 'lucide:box',
    users: 'lucide:users',
    list: 'lucide:layout-list',
    checkouts: 'lucide:copy-check',
    options: 'lucide:cog',
    globe: 'lucide:globe',
    book: 'lucide:book-open-text',
    gallery: 'lucide:gallery-horizontal-end',
    galleryItem: 'lucide:gallery-horizontal',
    monitorCheck: 'lucide:monitor-check',
    house: 'lucide:house',
    mapPinWarehouse: 'lucide:map-pin-house',
  },
})
